version: '3.2'

services:
  elasticsearch:
    image: pi1.wee:443/arm64v8/elasticsearch:7.10.1
#    container_name: elasticsearch
    environment:
#      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb

  cassandra:
    image: pi1.wee:443/arm64v8/cassandra:3.11.9
#    container_name: cassanddra
    environment:
      - CASSANDRA_CLUSTER_NAME=webit
    ports:
      - 7000:7000 # Cassandra inter-node cluster communication.
      - 7001:7001 # Cassandra SSL inter-node cluster communication.
      - 7199:7199 # Cassandra JMX monitoring port.
      - 9042:9042 # Cassandra client port.
      - 9160:9160 # Cassandra Thrift client port.
      - 9404:9404 # Prometheus plugin port.
    networks:
      - cassandra
    restart: always
    deploy:
      resources:
        limits:
          memory: 2gb
    volumes:
      - cassandra:/var/lib/cassandra

  webit-server:
    image: pi1.wee:443/arm64v8/webit-server-pi:latest
    ports:
      - 8080:8080
    depends_on:
      - cassandra
      - elasticsearch
    networks:
      - webit
      - cassandra
      - elasticsearch
    restart: always
    volumes:
      - /media/music/unprocessed:/media/music/unprocessed
      - /media/music/albums:/media/music/albums
      - /media/images:/media/images

  webit-webapp:
    image: pi1.wee:443/arm64v8/webit-webapp-pi:latest
    ports:
      - 80:80
    depends_on:
      - webit-server
    networks:
      - webit
    restart: always

volumes:
  elasticsearch:
    driver: local
  cassandra:
    driver: local

networks:
  elasticsearch:
    driver: bridge
  cassandra:
    driver: bridge
  webit:
    driver: bridge
